### PR TITLE
update for nextcloud v13.0.0 and v13.0.1

### PR DESCRIPTION
**Pull request by tuxedo-rb**
This update fixes mainly the calendar implementation and also the odd display layout.
I wrote and tested this fork under nextcloud v13.0.0 and v13.0.1

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Hi @daita fancy taking a look :) 
Cheers,
Danny :wink:

**Comment by AndyScherzinger** [comment]
Also üinging @schiessle and @juliushaertl just to be save :)

**Comment by daita** [comment]
Sorry I could not find the time to review this, it is a (really) big update.

I will try to find some time this week

**Comment by tuxedo-rb** [comment]
Understandable.
I think it's a bit difficult to check the fullcalendar files.
My Download folder shows March, 1st 2018 as dowload date.
As i can see on Adam Shaw's GitHub, there were still further commits until April, 4th 2018.
I can only assure you that i didn't touch the updated fullcalendar component in any way.

**Comment by juliushaertl** [comment]
I would prefer if we use some kind of dependency management to download an bump the fullcalendar dependency. So we can at least somehow make sure that the added files are the ones from the release.

**Comment by tuxedo-rb** [comment]
Hello Julius,
Excuse my late reply.
I've been involved in a higher priority project so far.
I'll work on the desired changes as soon as possible.

**Comment by daita** [comment]
Hey,
First, thanks for your patience !

This is some descent work in here, still a lot of space for improvement but at least, it gives a huge boost to the existing code.

Can you remove the vendor/* from your PR ?
Then I will merge to master and we can work on stronger base !

Regards,

(Thanks again for your PR !)

**Comment by tuxedo-rb** [comment]
Hello daita,
yes, sure.
Shall i delete components/* and composer.lock too?
And the entry for fullcalendar in composer.json is also wrong ("fullcalendar": "v3.8.2" instead of "fullcalendar/fullcalendar": "v3.8.2").

**Comment by daita** [comment]
keep composer.lock and remove components/

**Pull request merged**
