### PR TITLE
update for nextcloud v14 and v15

### PR DESCRIPTION
**Pull request by tuxedo-rb**
this pull request fixes the layout for nextcloud v14 (which refers to open issue #45),
removes the unused db-table 'dashboard_files',
adds theming app color for the section bottom borders, if theming app is installed (which refers to open issue #19)
and some minor fixes.

### CODE REVIEW

**Comment by daita** [comment]
I appreciate your time spent on this 'almost-deprecated' app. I will have a look to this as soon as possible

**Comment by tuxedo-rb** [comment]
No hurry.

Hmm, it seems Nextcloud v14 messed up more than only the layout.
The tinymce editor won't open to create/edit announcements. So the announcement section is totally unusable.
And if i click on a event in fullcalendar, no overlay opens (well, minor issue).
I'm not a javascript expert, so i don't know, how to fix this.

Does Nextcloud14 handle third-party javascript in a different way now?

**Comment by tuxedo-rb** [comment]
Ok, i've found the problem.
The main content overlaid the ui-elements.
I increased the css property 'z-index' for ui-elements.

**Comment by daita** [comment]
Do you see any issue for merging your work on stable14 and release it as a 14-only version ?

**Comment by tuxedo-rb** [comment]
That's ok for me.

**Comment by tuxedo-rb** [comment]
My latest commit fixes also issue [#18](https://github.com/nextcloud/dashboard/issues/18).
I replaced the sql function curdate() with a php generated date.

**Comment by tuxedo-rb** [comment]
I close this merge request, due to the age and changes on a publicly unused stale branch.

**Pull request closed without merging**
